# Purpose: Pre-commit hooks configuration for code quality enforcement
# Scope: Repository-wide automated code quality checks before commits
# Overview: Configures pre-commit hooks to run comprehensive linting and testing via Make targets.
#     Uses `make lint-all` for all code quality checks (Python linting, frontend linting,
#     complexity analysis, security scanning, and custom design linters) and `make test` for
#     full test suite execution. Also includes basic file quality checks like trailing whitespace,
#     file endings, and YAML/JSON validation.
# Dependencies: pre-commit, make, and all tools specified in Makefile targets
# Exports: Pre-commit hook configuration for the repository
# Interfaces: Triggered automatically on git commit, can be run manually with pre-commit run
# Implementation: Uses Make targets for comprehensive linting and testing, plus basic file checks

repos:

  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-json
        exclude: tsconfig.*\.json$
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: mixed-line-ending
        args: ['--fix=lf']

  # Comprehensive linting and testing
  - repo: local
    hooks:

      - id: make-lint-all
        name: Run comprehensive linting suite
        entry: make lint-all
        language: system
        pass_filenames: false
        stages: [pre-commit]
        verbose: true

      - id: make-test
        name: Run full test suite
        entry: make test
        language: system
        pass_filenames: false
        stages: [pre-commit]
        verbose: true
