repos:
  # Python hooks
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        files: ^durable-code-app/backend/

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]
        files: ^durable-code-app/backend/

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.9
    hooks:
      - id: ruff
        args: [--fix]
        files: ^durable-code-app/backend/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        files: ^durable-code-app/backend/

  # TypeScript/JavaScript hooks
  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: v8.56.0
  #   hooks:
  #     - id: eslint
  #       files: \.[jt]sx?$
  #       types: [file]
  #       additional_dependencies:
  #         - eslint@8.56.0
  #         - typescript@5.3.3
  #         - '@typescript-eslint/parser@6.17.0'
  #         - '@typescript-eslint/eslint-plugin@6.17.0'

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: ^durable-code-app/frontend/
        types_or: [javascript, jsx, ts, tsx, css, json]

  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-json
        exclude: tsconfig.*\.json$
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: mixed-line-ending
        args: ["--fix=lf"]

  # Security
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        args: ["-r", "durable-code-app/backend/app"]
        files: ^durable-code-app/backend/

  # Complexity check
  - repo: local
    hooks:
      - id: radon-complexity
        name: Check Python complexity
        entry: bash -c 'cd durable-code-app/backend && poetry run radon cc app -n A'
        language: system
        pass_filenames: false
        files: ^durable-code-app/backend/.*\.py$

      # - id: header-check
      #   name: Check file headers
      #   entry: python tools/design-linters/header_linter.py
      #   language: system
      #   pass_filenames: false
      #   args: ['--path', '.', '--recursive']
      #   files: \.(md|py|ts|tsx|js|jsx|html|yml|yaml)$
      #   exclude: ^(node_modules|\.git|\.venv|venv|__pycache__|build|dist)/

      # - id: print-statement-check
      #   name: Check for print statements
      #   entry: python tools/design-linters/print_statement_linter.py
      #   language: system
      #   pass_filenames: false
      #   args: ['--path', '.', '--recursive', '--format', 'text', '--no-skip-tests']
      #   files: \.(py|js|jsx|ts|tsx|mjs|cjs)$
      #   exclude: ^(node_modules|\.git|\.venv|venv|__pycache__|build|dist)/

      - id: breadcrumb-check
        name: Check HTML documentation for breadcrumbs
        entry: python tools/design-linters/breadcrumb_linter.py
        language: system
        pass_filenames: false
        files: \.html$
        exclude: ^(node_modules|\.git|\.venv|venv|__pycache__|build|dist|test|mock|template)/
