# Purpose: Pre-commit hooks configuration for code quality enforcement
# Scope: Repository-wide automated code quality checks before commits
# Overview: Configures comprehensive pre-commit hooks for Python and TypeScript/JavaScript projects
#     ensuring code quality standards are met before any code is committed. Includes formatting
#     tools (black for Python, prettier for JS/TS), import sorting (isort), linting (ruff, mypy),
#     security scanning (bandit), complexity analysis (radon), and custom design linters for
#     enforcing project-specific standards like header validation, breadcrumb checking, and
#     nesting depth limits. All hooks run automatically on git commit and can be manually
#     triggered for validation. The configuration supports file filtering by type and location.
# Dependencies: pre-commit, various linting tools specified in each hook
# Exports: Pre-commit hook configuration for the repository
# Interfaces: Triggered automatically on git commit, can be run manually with pre-commit run
# Implementation: Defines hooks for black, isort, ruff, mypy, prettier, bandit, radon, and custom linters

repos:
  # Python hooks
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        files: ^durable-code-app/backend/

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]
        files: ^durable-code-app/backend/

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.9
    hooks:
      - id: ruff
        args: [--fix]
        files: ^durable-code-app/backend/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        files: ^durable-code-app/backend/

  # TypeScript/JavaScript hooks
  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: v8.56.0
  #   hooks:
  #     - id: eslint
  #       files: \.[jt]sx?$
  #       types: [file]
  #       additional_dependencies:
  #         - eslint@8.56.0
  #         - typescript@5.3.3
  #         - '@typescript-eslint/parser@6.17.0'
  #         - '@typescript-eslint/eslint-plugin@6.17.0'

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: ^durable-code-app/frontend/
        types_or: [javascript, jsx, ts, tsx, css, json]

  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-json
        exclude: tsconfig.*\.json$
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: mixed-line-ending
        args: ['--fix=lf']

  # Security
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        args: ['-r', 'durable-code-app/backend/app']
        files: ^durable-code-app/backend/

  # Complexity check
  - repo: local
    hooks:
      - id: radon-complexity
        name: Check Python complexity
        entry: bash -c 'cd durable-code-app/backend && poetry run radon cc app -n A'
        language: system
        pass_filenames: false
        files: ^durable-code-app/backend/.*\.py$

      # - id: header-check
      #   name: Check file headers
      #   entry: python tools/design_linters/header_linter.py
      #   language: system
      #   pass_filenames: false
      #   args: ['--path', '.', '--recursive']
      #   files: \.(md|py|ts|tsx|js|jsx|html|yml|yaml)$
      #   exclude: ^(node_modules|\.git|\.venv|venv|__pycache__|build|dist)/

      # - id: print-statement-check
      #   name: Check for print statements
      #   entry: python tools/design_linters/print_statement_linter.py
      #   language: system
      #   pass_filenames: false
      #   args: ['--path', '.', '--recursive', '--format', 'text', '--no-skip-tests']
      #   files: \.(py|js|jsx|ts|tsx|mjs|cjs)$
      #   exclude: ^(node_modules|\.git|\.venv|venv|__pycache__|build|dist)/

      - id: breadcrumb-check
        name: Check HTML documentation for breadcrumbs
        entry: python tools/design_linters/breadcrumb_linter.py
        language: system
        pass_filenames: false
        files: \.html$
        exclude: ^(node_modules|\.git|\.venv|venv|__pycache__|build|dist|test|mock|template)/
