name: Playwright Integration Tests

on:
  push:
    branches: [main, develop, feature/*]
  pull_request:
    branches: [main, develop]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start services
        run: make dev-start

      - name: Wait for services
        run: |
          echo "Waiting for frontend..."
          timeout 60 bash -c 'until curl -s http://localhost:5570 > /dev/null; do sleep 1; done'
          echo "Waiting for backend..."
          timeout 60 bash -c 'until curl -s http://localhost:8397/health > /dev/null; do sleep 1; done'

      - name: Build Playwright container
        run: make test-playwright-build

      - name: Run oscilloscope tests
        run: make test-playwright-oscilloscope

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: |
            test-results/
            playwright-report/

      - name: Stop services
        if: always()
        run: make dev-stop
